build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==0.34.2"
    - "diffusers==0.30.2"
    - "pillow==10.4.0"
    - "torch==2.4.1"
    - "transformers==4.44.2"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.25.2"
